### ISSUE TITLE
AppVeyor broken

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/pytest-pep8-feedstock#1]
Appears the repo got created on AppVeyor. However, there is no pending build and trying to start a build fails. Any ideas, @pelson?

**Comment by bjodah** [comment]
Looks to be queued in #2

**Comment by jakirkham** [comment]
Well that's good. Had no luck with `master` earlier. Will retry.

**Comment by jakirkham** [comment]
Was able to retrigger through the webhooks. Also reshuffled the builds so that `master` will build before that PR does FYI.
